# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ssl_vision_wrapper.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import ssl_vision_detection_pb2 as proto_dot_ssl__vision__detection__pb2
from proto import ssl_vision_geometry_pb2 as proto_dot_ssl__vision__geometry__pb2
from proto import ssl_vp_config_pb2 as proto_dot_ssl__vp__config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eproto/ssl_vision_wrapper.proto\x1a proto/ssl_vision_detection.proto\x1a\x1fproto/ssl_vision_geometry.proto\x1a\x19proto/ssl_vp_config.proto\"\x9c\x01\n\x11SSL_WrapperPacket\x12&\n\tdetection\x18\x01 \x01(\x0b\x32\x13.SSL_DetectionFrame\x12#\n\x08geometry\x18\x02 \x01(\x0b\x32\x11.SSL_GeometryData\x12\x1b\n\x06source\x18\x03 \x01(\x0e\x32\x0b.SSL_Source\x12\x1d\n\x06\x63onfig\x18\x04 \x01(\x0b\x32\r.SSL_VPConfig*\xa8\x01\n\nSSL_Source\x12\x16\n\x12SSL_SOURCE_UNKNOWN\x10\x00\x12\x14\n\x10SSL_SOURCE_OTHER\x10\x01\x12\x19\n\x15SSL_SOURCE_SSL_VISION\x10\x02\x12\x1f\n\x1bSSL_SOURCE_VISION_PROCESSOR\x10\x03\x12\x14\n\x10SSL_SOURCE_GRSIM\x10\x04\x12\x1a\n\x16SSL_SOURCE_ERFORCE_SIM\x10\x05')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.ssl_vision_wrapper_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SSL_SOURCE._serialized_start=288
  _SSL_SOURCE._serialized_end=456
  _SSL_WRAPPERPACKET._serialized_start=129
  _SSL_WRAPPERPACKET._serialized_end=285
# @@protoc_insertion_point(module_scope)
