services:
  ai:
    network_mode: host

  game-viewer:
    environment:
      - SSL_VISION_MULTICAST_PORT=${SSL_VISION_REAL_MAIN_PORT}
    depends_on:
      - ${DOCKER_NAME_AI}
    network_mode: host

  ssl-vision-client:
    command:
      - "-visionAddress"
      - "${SSL_VISION_MULTICAST_ADDR}:${SSL_VISION_REAL_MAIN_PORT}"
    network_mode: host

  ssl-game-controller:
    command:
      - "-visionAddress"
      - "${SSL_VISION_MULTICAST_ADDR}:${SSL_VISION_REAL_MAIN_PORT}"
      - "-trackerAddress"
      - "${SSL_VISION_MULTICAST_ADDR}:${SSL_VISION_REAL_MAIN_PORT}"
      - "-publishAddress"
      - "${SSL_GAME_CONTROLLER_PUBLISH_ADDR}:${SSL_GAME_CONTROLLER_PUBLISH_PORT}"
      - "-address"
      - ":${SSL_GAME_CONTROLLER_UI_PORT}"
    network_mode: host

  er-sim:
    profiles:
      - donotstart

  tiger-auto-referee:
    image: tigersmannheim/auto-referee   # headless image
    container_name: ${DOCKER_NAME_TIGER_AUTOREF}
    restart: "no"
    network_mode: "host"                 # required for multicast
    command:
      - "-hl"
      - "-va"
      - "${SSL_VISION_MULTICAST_ADDR}:${SSL_VISION_REAL_MAIN_PORT}"
