services:
  ai:
    environment:
      - ENVIRONMENT=competition
    network_mode: "host"

  game-viewer:
    environment:
      - ENVIRONMENT=competition
      - SSL_VISION_MULTICAST_ADDR=${SSL_VISION_MULTICAST_ADDR}
      - SSL_VISION_MULTICAST_PORT=${SSL_VISION_REAL_MAIN_PORT}
    command: pnpm run dev
    network_mode: "host"

  ssl-vision-client:
    network_mode: "host"

  # ssl-game-controller:
  #   profiles:
  #     - donotstart

  er-sim:
    profiles:
      - donotstart

  tiger-auto-referee:
    profiles:
      - donotstart
