services:
  ai:
    environment:
      - ENVIRONMENT=competition
      - VITE_AI_GAME_VIEWER_SOCKET_ADDR=192.168.1.1
    network_mode: host

  game-viewer:
    environment:
      - ENVIRONMENT=competition
      - SSL_VISION_MULTICAST_PORT=${SSL_VISION_REAL_MAIN_PORT}
      - VITE_AI_GAME_VIEWER_SOCKET_ADDR=192.168.1.1
    command: bash -c "cd /var/GameViewer && pnpm install && pnpm run dev"
    network_mode: host

  ssl-vision-client:
    command:
      - "-visionAddress"
      - "${SSL_VISION_MULTICAST_ADDR}:${SSL_VISION_REAL_MAIN_PORT}"
    network_mode: host

  ssl-game-controller:
    command:
      - "-visionAddress"
      - "${SSL_VISION_MULTICAST_ADDR}:${SSL_VISION_REAL_MAIN_PORT}"
      - "-trackerAddress"
      - "${SSL_VISION_MULTICAST_ADDR}:${SSL_VISION_REAL_MAIN_PORT}"
      - "-publishAddress"
      - "${SSL_GAME_CONTROLLER_PUBLISH_ADDR}:${SSL_GAME_CONTROLLER_PUBLISH_PORT}"
      - "-address"
      - ":${SSL_GAME_CONTROLLER_UI_PORT}"
    network_mode: host

  er-sim:
    profiles:
      - donotstart
